# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Delete assetlinks.json

on:
  push:
    branches:
      - main

jobs:
  delete-assetlinks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Sleep for 5 minutes
      run: sleep 300
      
    - name: Delete assetlinks.json
      run: |
        rm .well-known/assetlinks.json
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git commit -m "Delete assetlinks.json" -a
        git push
